### ISSUE TITLE
Known Issue: Plugin fails to load on Dalamud 10.0.0.2

### ISSUE THREAD

**Issue by foophoof** [foophoof/CollectorsAnxiety#16]
The addition of Facewear support added a dependency on Lumina.Excel 7.0.1, which has not yet landed in the release version of Dalamud, so currently the plugin only loads correctly on the staging branch of Dalamud.

This should get fixed on the next release of Dalamud.

If you try to load the plugin, an error similar to this will be in the log:

```
[ERR] [LOCALPLUGIN] Could not load one or more types when searching for IDalamudPlugin: C:\Users\user\AppData\Roaming\XIVLauncher\installedPlugins\CollectorsAnxiety\0.0.8.0\CollectorsAnxiety.dll
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'Lumina.Excel.GeneratedSheets.GlassesStyle' from assembly 'Lumina.Excel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Lumina.Excel.GeneratedSheets.GlassesStyle' from assembly 'Lumina.Excel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Dalamud.Plugin.Internal.Types.LocalPlugin.EnsureLoader() in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 685
System.TypeLoadException: Could not load type 'Lumina.Excel.GeneratedSheets.GlassesStyle' from assembly 'Lumina.Excel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Lumina.Excel.GeneratedSheets.GlassesStyle' from assembly 'Lumina.Excel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
[ERR] [LOCALPLUGIN] Exception in plugin constructor
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'Lumina.Excel.GeneratedSheets.GlassesStyle' from assembly 'Lumina.Excel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'Lumina.Excel.GeneratedSheets.GlassesStyle' from assembly 'Lumina.Excel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Dalamud.Plugin.DalamudPluginInterface.GetPluginConfig() in C:\goatsoft\companysecrets\dalamud\\Plugin\DalamudPluginInterface.cs:line 398
   at CollectorsAnxiety.CollectorsAnxietyPlugin..ctor(IDalamudPluginInterface pluginInterface) in S:/CollectorsAnxietyPlugin.cs:line 36
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.TypeLoadException: Could not load type 'Lumina.Excel.GeneratedSheets.GlassesStyle' from assembly 'Lumina.Excel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'Lumina.Excel.GeneratedSheets.GlassesStyle' from assembly 'Lumina.Excel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 130
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 431
[LOCALPLUGIN] Error while loading CollectorsAnxiety, failed to bind and call the plugin constructor
```

**Comment by foophoof** [comment]
This is fixed on Dalamud 10.0.0.3 which is now released. #20 should also help me ensure I don't do this again in the future.
